### PR TITLE
[Fix] Typescript

### LINKED ISSUE #8: Fix types

### PR DESCRIPTION
**Pull request by joshuaellis**
So, I went through the `src` and fixed the TS errors, hopefully without breaking anything. The examples currently work, but I'll go through those after posting this and solve that to double check my work. Fun fact: the default export is exactly what the `react` team do for `Context` so I could then see how the `@types` wrote the TS impl.

Happy to answer any Q's & amend any follys of course.

### CODE REVIEW

**Comment by gsimone** [comment]
Can you add a TS codesandbox to see this running? (that I'll eventually add to CI so we can refer to it)

**Comment by joshuaellis** [comment]
Sure, let me sort of the example app, because that's ironing out a few TS issues & I'll add a sandbox afterwards so we can critique further.

**Comment by joshuaellis** [comment]
Here's a [sandbox](https://codesandbox.io/s/component-material-ts-d3ds3?file=/src/App.tsx). Take no credit for the material work, I just copied my fave from the example repo lol.

**Comment by emmelleppi** [comment]
With the build made by codesandbox I still have two errors.

https://codesandbox.io/s/component-material-ts-forked-zerpl?file=/src/Scene.tsx

- One concerning the Head component 

```
Property 'Head' does not exist on type 'ShaderProxyHelper<"body" | "head" |....
```
it should be because it is not defined Head in the ShaderProxyHelper, right?

```js
type ShaderProxyHelper<T extends string> = {
  [key in T]: any;
} & {
  Body: any;
  // missing Head type here?
};
```


- Another one concerning the Common component

```
This JSX tag's 'children' prop expects type 'string[]' which requires multiple children, but only a single child was provided.ts(2745)

'M.Common' cannot be used as a JSX component.
 Its return type 'string[]' is not a valid JSX element.
 Type 'string[]' is missing the following properties from type 'Element': type, props, keyts(2786)
 ```
 
 That's because the `common` proxy is defined like this
 
 ```js
 export function common({ children }: ProxyProps) {
  return children
}
 ```
 but, unlike the `fragment` and `vertex` proxies, the `common` must simply take the child (which is a string) and return it as it is. Then the parent (`ComponentMaterial`) for each child will do this
 
 ```js
      const shader = child?.props?.children

      if (typeof shader === 'string') {
        const { shaderType }: ChildProps = child.type

        if ([VERT, FRAG].includes(shaderType)) {
           // we don't mind
        } else {
          // everything that is not vert or frag is common. to do better in the future lol
          acc.common = acc.common.concat(`
            ${shader}
          `)
        }
     }
 ```
 Maybe we need a type specifically for `common`?

**Comment by joshuaellis** [comment]
@emmelleppi for the common component, we should return `children` from `common` wrapped in a `React.Fragment`, see [here](https://stackoverflow.com/questions/62075694/jsx-element-type-string-is-not-a-constructor-function-for-jsx-elements-typesc). The other part about it being `string[]` in `ProxyProp` we can write a generic, like i've done for `useLoader` in r3f that will handle either a `string | string[]`. 

The `Head` is a bit odd, I think you're probably right, it's missing from `ShaderProxyHelper` but should it be `any`? What's it supposed to be lol?

**Comment by emmelleppi** [comment]
I was going to share a codesandbox in which I had made the fix of the `common` type, but I have seen that you have already done it and in a better way 😅

For `Head`, if you add it as type `any` of course it works, however it's just a workaround.

```js
type ShaderProxyHelper<T extends string> = {
  [key in T]: any;
} & {
  Body: any;
  Head: any;
};

const vertHandler = {
  get: function (_: any, name: string) {
    const Component = function ({ children }: ProxyProps) {
      return children;
    };
    Object.defineProperty(Component, "chunkName", { writable: true });
    Object.defineProperty(Component, "shaderType", { writable: true });
    Component.chunkName = name === "Body" ? DEFAULT_VERT_CHUNK : name;
    Component.shaderType = VERT;
    return Component;
  }
};

export const vert: ShaderProxyHelper<vertexChunks | commonChunks> = new Proxy(
 () => null,
  vertHandler
);
```
`Head` (in the same way as `Body` and `T`) is the second argument passed to the `get()` function of the Proxy handler and represents the name of the chunk to be edited (`alphamap_fragment`, `alphamap_pars_fragment`, etc).
Obviously we invented `Head` and `Body`, as shortcuts for the chunks `project_vertex` and `dithering_fragment` respectively.
So they should be of the type function that returns `Component`?

Also, I had missed one last TS error for the ref 😬
https://codesandbox.io/s/component-material-ts-forked-zerpl?file=/src/Scene.tsx:944-967
I don't really know how to handle this one 😞

**Comment by joshuaellis** [comment]
> Also, I had missed one last TS error for the ref 😬
https://codesandbox.io/s/component-material-ts-forked-zerpl?file=/src/Scene.tsx:944-967
I don't really know how to handle this one 😞

This is fixed by changing the first arg of `React.forwardRef` from `THREE.Material` to `GenericMaterial` which extends `THREE.Material` so we should be fine. 

The only issue after that is the props you pass such as `clearcoat` i'll need to do more looking into that 🔍  The stuff about `Head` i'll look at later too 👍🏼

**Comment by joshuaellis** [comment]
So the missing piece of the puzzle (I think) is how to handle props. So currently the example uses `clearcoat` which I can't see it doing anything, is this because it's a prop on `MeshPhysicalMaterial` which is what the initial component is based on?

Basically, my only idea is to combine all the Material Types together: 
```ts
type MatProps = MaterialProps & MeshPhysicalMaterialProps & ....
export type ComponentMaterialProps = MatProps & {
  varyings?: Varyings
  uniforms?: Uniforms
  from?: MaterialConstructor
}
```
because I think adding [key: string]: any is dangerous.... Unless you want to accept `any` prop??

I've updated my sandbox above too.

**Comment by joshuaellis** [comment]
Hey, @emmelleppi any thoughts on the above?

**Comment by emmelleppi** [comment]
Oh sorry I had missed your comment!

> is this because it's a prop on `MeshPhysicalMaterial` which is what the initial component is based on?

Exactly
By default `component-material` extends `MeshPhysicalMaterial`, which is in fact the most complete material of threejs.
But, despite this I don't think that only with `MeshPhysicalMaterial` is enough to cover all possible attributes, I immediately think of the `MeshMatcapMaterial`, which has exclusive attributes only for it. 

So...

> Basically, my only idea is to combine all the Material Types together

I guess it makes sense, 90% of the attributes will be overridden because they are all shared by materials, but I don't think the code police will come along 🤷🏻‍♂️

Does it make sense to you?

**Comment by joshuaellis** [comment]
That did make sense!

>  but I don't think the code police will come along 🤷🏻‍♂️

If they do come along maybe they can fix it for us lol. I'm pretty sure you could do with some `Generic` magic, but it's beyond me right now.

**Pull request merged**
